# Generated by Django 4.2.2 on 2023-06-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedpost',
            old_name='post',
            new_name='content_object',
        ),
        migrations.AlterUniqueTogether(
            name='taggedpost',
            unique_together={('content_object', 'tag')},
        ),
    ]
