# Generated by Django 4.2.2 on 2023-06-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='No summary was provided.', max_length=100),
        ),
    ]
