# Generated by Django 4.2.7 on 2023-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='user-profile.jpeg', upload_to='user_images/'),
        ),
    ]
