# Generated by Django 4.2.14 on 2024-10-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='defaults/default-image.png', upload_to='user_images/'),
        ),
    ]
