# Generated by Django 4.2.14 on 2024-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/25c93125-bd78-407b-930d-a430f0f23ec4/b4c86719-0619-4bd2-b3f1-b14a25982b43.png'),
        ),
    ]
