# Generated by Django 4.2.3 on 2023-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(),
        ),
    ]
