name: Personal Blog CI

on:
  push:
    branches: [ dev001 ]
  pull_request:
    branches: [ dev001 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      uses: python manage.py collectstatic --noinput