name: Deploy to Production

on:
  push:
    branches:
      - main  # Update this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Choose your desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Copy environment files
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            cp .env.prod .env
            cp project/settings_prod.py project/settings.py
          else
            cp .env.dev .env
            cp project/settings_dev.py project/settings.py
          fi

